### ISSUE TITLE
[BUG] Error on shutdown

### ISSUE THREAD

**Issue by WolfiiYV** [YVtils/YVtils-SMP#24]
**To Reproduce**
1. Start Server with plugin
2. Wait some time
3. (Join the server)
4. Shutdown serve

**Server (please complete the following information):**
 - Software: Purpur
 - Plugin Version: 1.0.1
 - Minecraft Version: 1.21.1

**Logs (please append a error / the logs if possible)**
```text
[23:03:21 ERROR]: [net.dv8tion.jda.api.requests.RestAction] RestAction queue returned failure: [ErrorResponseException] 10008: Unknown Message
net.dv8tion.jda.api.exceptions.ContextException: null
at YVtils-SMP_v1.0.1.jar/net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54) ~[YVtils-SMP_v1.0.1.jar:?]
at YVtils-SMP_v1.0.1.jar/net.dv8tion.jda.api.requests.Request.<init>(Request.java:77) ~[YVtils-SMP_v1.0.1.jar:?]
at YVtils-SMP_v1.0.1.jar/net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:203) ~[YVtils-SMP_v1.0.1.jar:?]
at YVtils-SMP_v1.0.1.jar/net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:573) ~[YVtils-SMP_v1.0.1.jar:?]
at YVtils-SMP_v1.0.1.jar/net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:539) ~[YVtils-SMP_v1.0.1.jar:?]
at YVtils-SMP_v1.0.1.jar/yv.tils.smp.mods.discord.whitelist.SelfAdd.onMessageReceived(SelfAdd.kt:50) ~[YVtils-SMP_v1.0.1.jar:?]
at YVtils-SMP_v1.0.1.jar/net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:455) ~[YVtils-SMP_v1.0.1.jar:?]
at YVtils-SMP_v1.0.1.jar/net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:98) ~[YVtils-SMP_v1.0.1.jar:?]
at YVtils-SMP_v1.0.1.jar/net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88) ~[YVtils-SMP_v1.0.1.jar:?]
at YVtils-SMP_v1.0.1.jar/net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70) ~[YVtils-SMP_v1.0.1.jar:?]
at YVtils-SMP_v1.0.1.jar/net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:169) ~[YVtils-SMP_v1.0.1.jar:?]
at YVtils-SMP_v1.0.1.jar/net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:138) ~[YVtils-SMP_v1.0.1.jar:?]
at YVtils-SMP_v1.0.1.jar/net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39) ~[YVtils-SMP_v1.0.1.jar:?]
at YVtils-SMP_v1.0.1.jar/net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:1009) ~[YVtils-SMP_v1.0.1.jar:?]
at YVtils-SMP_v1.0.1.jar/net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:892) ~[YVtils-SMP_v1.0.1.jar:?]
at YVtils-SMP_v1.0.1.jar/net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:870) ~[YVtils-SMP_v1.0.1.jar:?]
at YVtils-SMP_v1.0.1.jar/net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1048) ~[YVtils-SMP_v1.0.1.jar:?]
at YVtils-SMP_v1.0.1.jar/com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[YVtils-SMP_v1.0.1.jar:?]
at YVtils-SMP_v1.0.1.jar/com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[YVtils-SMP_v1.0.1.jar:?]
at YVtils-SMP_v1.0.1.jar/com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[YVtils-SMP_v1.0.1.jar:?]
at YVtils-SMP_v1.0.1.jar/com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[YVtils-SMP_v1.0.1.jar:?]
at YVtils-SMP_v1.0.1.jar/com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[YVtils-SMP_v1.0.1.jar:?]
at YVtils-SMP_v1.0.1.jar/com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[YVtils-SMP_v1.0.1.jar:?]
at YVtils-SMP_v1.0.1.jar/com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[YVtils-SMP_v1.0.1.jar:?]
```

**Comment by WolfiiYV** [comment]
Also discord voice channels not getting deleted on shutdown could be related.

(Could also be only some hoster thing with gportal)

**Comment by WolfiiYV** [comment]
Wrong error.

I meant this one:

```text
[18:16:05] [Server thread/ERROR]: Error occurred while disabling YVtils-SMP v1.0.0
java.util.ConcurrentModificationException: null
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1095) ~[?:?]
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1049) ~[?:?]
	at YVtils-SMP_paper-1.0.0-all.jar/yv.tils.smp.mods.waypoints.WaypointPath.stopNavigations(WaypointPath.kt:296) ~[YVtils-SMP_paper-1.0.0-all.jar:?]
	at YVtils-SMP_paper-1.0.0-all.jar/yv.tils.smp.manager.shutdown.Modules.shutdown(Modules.kt:8) ~[YVtils-SMP_paper-1.0.0-all.jar:?]
	at YVtils-SMP_paper-1.0.0-all.jar/yv.tils.smp.manager.shutdown.Summarizer.shutdown(Summarizer.kt:8) ~[YVtils-SMP_paper-1.0.0-all.jar:?]
	at YVtils-SMP_paper-1.0.0-all.jar/yv.tils.smp.YVtils.onDisable(YVtils.kt:67) ~[YVtils-SMP_paper-1.0.0-all.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.jar:1.21-127-4e6a2a1]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:161) ~[paper-1.21.jar:1.21-127-4e6a2a1]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:97) ~[paper-1.21.jar:1.21-127-4e6a2a1]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:541) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.disablePlugins(CraftServer.java:609) ~[paper-1.21.jar:1.21-127-4e6a2a1]
	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:1046) ~[paper-1.21.jar:1.21-127-4e6a2a1]
	at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:847) ~[paper-1.21.jar:1.21-127-4e6a2a1]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1353) ~[paper-1.21.jar:1.21-127-4e6a2a1]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-127-4e6a2a1]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
